
compile:
	cd ./Code && make all

clean:
	cd ./Code && make clean

nessaryTest:compile test1 test2 test3

allTest:compile test1 test2 test3 test4 test5 test6 test7 test8 test9 test10


test1: ./Code/parser ./TestCase/test1.cmm
	$(info >>>>>test1)
	./Code/parser ./TestCase/test1.cmm
test2: ./Code/parser ./TestCase/test2.cmm
	$(info >>>>>test2)
	./Code/parser ./TestCase/test2.cmm
test3: ./Code/parser ./TestCase/test3.cmm
	$(info >>>>>test3)
	./Code/parser ./TestCase/test3.cmm
test4: ./Code/parser ./TestCase/test4.cmm
	$(info >>>>>test4)
	./Code/parser ./TestCase/test4.cmm
test5: ./Code/parser ./TestCase/test5.cmm
	$(info >>>>>test5)
	./Code/parser ./TestCase/test5.cmm
test6: ./Code/parser ./TestCase/test6.cmm
	$(info >>>>>test6)
	./Code/parser ./TestCase/test6.cmm
test7: ./Code/parser ./TestCase/test7.cmm
	$(info >>>>>test7)
	./Code/parser ./TestCase/test7.cmm
test8: ./Code/parser ./TestCase/test8.cmm
	$(info >>>>>test8)
	./Code/parser ./TestCase/test8.cmm
test9: ./Code/parser ./TestCase/test9.cmm
	$(info >>>>>test9)
	./Code/parser ./TestCase/test9.cmm
test10: ./Code/parser ./TestCase/test10.cmm
	$(info >>>>>test10)
	./Code/parser ./TestCase/test10.cmm